site_name: 'TIBCO Flogo Extension Generators'
site_description: 'TIBCO Flogo Extension Generators'

nav:
  - Introduction: ./index.md
  - Activity Scaffolder: ./simple-activity-generator/flogo-activity-extension-scaffolder.md
  - Trigger Scaffolder: ./simple-trigger-generator/flogo-trigger-extension-scaffolder.md
  - Function Scaffolder: ./simple-function-generator/flogo-function-extension-scaffolder.md


plugins:
  - techdocs-core