site_name: 'TIBCO Flogo Extension Generators'
site_description: 'TIBCO Flogo Extension Generators'

nav:
  - Introduction: ./index.md
  - Activity Scaffolder: ./flogo-activity-extension-scaffolder.md
  - Trigger Scaffolder: ./flogo-trigger-extension-scaffolder.md
  - Function Scaffolder: ./flogo-function-extension-scaffolder.md


plugins:
  - techdocs-core